# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/build_xilinx/RiscV_WebSoC.runs/synth_1/webserver_cpu_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/build_xilinx/RiscV_WebSoC.cache/wt [current_project]
set_property parent.project_path /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/build_xilinx/RiscV_WebSoC.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/build_xilinx/RiscV_WebSoC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/axi2lcpu.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/clock_frequency_divider.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/cpu_channel.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/crc.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/define.sv
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/dual_clock_fifo.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/dual_clock_simple_dual_port_ram.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/eth_presemble.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/fix_delay.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/fpga_build_time.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/gmii2mac.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/gmii_to_rgmii.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/jtag_cpu_xilinx.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/lcpu_fpga_test.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/lcpu_merge.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/lcpu_riscv_wrapper.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/lcpu_top.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/mac_rx.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/mac_top.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/mac_tx.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/mmcm_50_125.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/package_fifo_v2.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/picorv32.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/pktfifo2ram_int_v2.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/pulse_clock_region_pass.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/ram2pktfifo_int.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/ramintf.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/rgmii_gmii_bridge.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/rgmii_to_gmii.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/riscv32_localbus.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/riscv32_top.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/riscv32intfbridge.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/riscv_reg.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/single_clock_fifo.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/single_clock_simple_dual_port_ram.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/single_clock_true_dual_port_ram.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/sop_eop_gen.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/uart.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/uart_lcpu.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/uart_lcpu_top.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/uart_rx.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/uart_tx.v
  /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/rtl/webserver_cpu_top.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/build_xilinx/pins.xdc
set_property used_in_implementation false [get_files /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/build_xilinx/pins.xdc]

read_xdc /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/build_xilinx/timing.xdc
set_property used_in_implementation false [get_files /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/build_xilinx/timing.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/minkey/work/RiscV_WebSoC_v1/RiscV_WebSoC/build_xilinx/RiscV_WebSoC.srcs/utils_1/imports/synth_1/webserver_cpu_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top webserver_cpu_top -part xc7a35tfgg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef webserver_cpu_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file webserver_cpu_top_utilization_synth.rpt -pb webserver_cpu_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
